#pragma once


#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 256
#define SCREEN_SIZE SCREEN_WIDTH * SCREEN_HEIGHT

#define _RASTERDEBU //_RASTERDEBUG
#define _SHADERDEBU //_SHADERDEBUG

#define PI 3.14159265358979f